spring:
  datasource:
    url: jdbc:mysql://localhost:3306/groduation?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: gan
    password: gan123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.graduatedsign.mapper

server:
  port: 8090